### ISSUE TITLE
Http adapter showing "connected" status even if nothing running on designated server

### ISSUE THREAD

**Issue by vanch3d** [hivemq/hivemq-edge#108]
## Expected behavior
An active HTTP adapter should not indicate `connected` when it is blatant that the server is not running. 

## Actual behavior

![Image](https://user-images.githubusercontent.com/2743481/268074172-8b358b0a-c610-48c6-af76-0e9f1b306819.png)

![Image](https://user-images.githubusercontent.com/2743481/268074470-f27e9cd5-a156-4131-9d4f-f7344e350db6.png)

Both the frontend and the backend accept a clearly fake URL. Upon creation, the active adapter is updated and the status switches to `connected` 

## To Reproduce
Creating an HTTP adapter with the URL: http://fake  

## Details
Other adapters like MODBUS or OPC-UA are shown as `disconnected` when the "URL" of the service is not a live system.

Note: there is also a question as to `http://fake` is a valid URL

**Comment by sfrehse** [comment]
Is this related to https://github.com/hivemq/hivemq-edge/issues/106 ?

**Comment by vanch3d** [comment]
> Is this related to #106 ?

Possibly. If there is a problem with parsing valid URL, then both connection status and validity might be in jeopardy

**Comment by simon622** [comment]
No, this is unrelated to the pattern regex issue. This is a fundamental system convention. As discussed in the call, we will change the enum values for the status field of a connection to:

* Started
* Stopped
* Error

This means even a connectionless adapters (like HTTP) can be reported using the shared status convention.

**Comment by simon622** [comment]
The proposal is now to have 2 separate fields on the connection status object, one for determining the status of the adapter, and one the status of any underlying connection.
