### ISSUE TITLE
Pattern-based validations need a better UX approach

### ISSUE THREAD

**Issue by vanch3d** [hivemq/hivemq-edge#109]
## Expected behaviour
The error message for the validation of a `url` field should tell _humans_ what the error is about, not regex parser :-)

## Actual behaviour

The standard error message for a `pattern` attribute of a `JSONSchema string is literally transcribing the wronged regular expression. Which, in the case of a `url`, can be long and unreadable, therefore unusable

![Image](https://user-images.githubusercontent.com/2743481/268077227-eb26630d-ef68-4640-bd00-41e798504c2f.png)

## To Reproduce
Creating an HTTP adapter with an incorrect URL, like in #106

## Details
- consider the implication for both (or either) backend and frontend validation
- human-readable (short?) statement would be better (suggestion, drop the printout of the regex) 
- in the frontend, consider using destructured validation to pinpoint errors and utilise field-associated error messages:
  - the domain `xxx` is not valid
  - the protocol `httpxyz` is not valid

**Comment by simon622** [comment]
I will ensure that the HTTP adapter uses the URL format and the pattern is removed
