### ISSUE TITLE
UNS Button text only makes sense for first use

### ISSUE THREAD

**Issue by simon622** [hivemq/hivemq-edge#125]
The UNS CTA is a button that reads "+ Setup a unified namespace". This works great for first use or when there is no UNS defined. We should detect is there is a UNS setup already and change the text of the button accordingly... when one is setup the button text should read:

"Modify unified namespace"

![Screenshot 2023-09-20 at 18 26 11](https://github.com/hivemq/hivemq-edge/assets/2924684/da6dfb39-49ee-4dfd-b3f8-dbc85be2a48b)

**Comment by vanch3d** [comment]
There is no definition of "setup" in the payload received from the API. All the properties are optional. The closest to a hard definition is the `enabled` property, used on the main page. The payload is already populated by default: 

```json
{
  "enabled" : true,
  "prefixAllTopics" : true,
  "enterprise" : "enterprise",
  "site" : "site",
  "area" : "area",
  "productionLine" : "production-line",
  "workCell" : "work-cell"
}
```

Modifying the button to read "Modify unified namespace"
