### ISSUE TITLE
Docs on loading a config file

### ISSUE THREAD

**Issue by lieberlois** [hivemq/hivemq-edge#157]
## Problem or use case

I want to setup hivemq edge instances with bridges to an enterprise hivemq cluster. I want to deploy this declaratively. The issue is, that I have not found any documentation on how to setup a hivemq bridge with a config.xml file.

## Preferred solution or suggestions

Provide examples or documentation for a) loading a configuration file and b) setting up a hivemq bridge with a configuration file.

**Comment by lieberlois** [comment]
Through trial and error, i found the following config, that works for me now.

```xml
<?xml version="1.0"?>
<hivemq>
    <mqtt-listeners>
        <tcp-listener>
            <port>1883</port>
            <bind-address>0.0.0.0</bind-address>
        </tcp-listener>
    </mqtt-listeners>
    <mqtt-sn-listeners>
        <udp-listener>
            <port>2442</port>
            <bind-address>0.0.0.0</bind-address>
        </udp-listener>
    </mqtt-sn-listeners>
    <admin-api>
        <enabled>true</enabled>
        <listeners>
            <http-listener>
                <bind-address>0.0.0.0</bind-address>
                <port>8080</port>
            </http-listener>
        </listeners>
    </admin-api>
    <mqtt-bridges>
        <mqtt-bridge>
            <id>site-1-to-cloud</id>
            <remote-broker>
                <host>1.2.3.4</host>
                <port>1883</port>
            </remote-broker>
            <forwarded-topics>
                <forwarded-topic>
                    <filters>
                        <mqtt-topic-filter>#</mqtt-topic-filter>
                    </filters>
                    <destination>{#}</destination>
                </forwarded-topic>
            </forwarded-topics>
        </mqtt-bridge>
    </mqtt-bridges>
</hivemq>
```

**Comment by simon622** [comment]
Thanks for this; documentation is available on the wiki. Specifically relating to bridging. Alternatively, you can use the UI to generate your bridged and allow he configuration file to be written for you by the system.

https://github.com/hivemq/hivemq-edge/wiki/MQTT-Bridging
