### ISSUE TITLE
Documentation for opc ua adapter is missing

### ISSUE THREAD

**Issue by KoenR3** [hivemq/hivemq-edge#25]
## Problem or use case
Currently the section for the OPCUA adapter in the documentation is empty.

## Preferred solution or suggestions
Add documentation into the section or, if not available, add text indicating this.

**Comment by simon622** [comment]
This documentation has been written, and once reviewed it will be made available. 

Thanks for the input.

**Comment by simon622** [comment]
This documentation is now available on the WIKI at the following link. There will also be custom configuration examples provided in the next release.

https://github.com/hivemq/hivemq-edge/wiki/Protocol-adapters#opc-ua-adapter
