### ISSUE TITLE
OPC UA Protocol Adapter - Subscribe directly to FolderType objects

### ISSUE THREAD

**Issue by prairiesnpr** [hivemq/hivemq-edge#342]
## Problem or use case
When configuring subscriptions for the OPC UA protocol adapter, it would be cleaner to subscribe to an object, in this case of type FolderType, instead of subscribing to each individual tag.

For example, if I want to subscribe to Tag.P101, I need to subscribe to the following tags.
- Tag.P101.AFLT
- Tag.P101.ATRIPD
- Tag.P101.ILOK
- Tag.P101.NAUTO
- Tag.P101.NEBL
- Tag.P101.NINHIBIT
- Tag.P101.NMM
- Tag.P101.NSTP
- Tag.P101.NSTRT
- Tag.P101.PRMT
- Tag.P101.QMODE
- Tag.P101.QSTOP
- Tag.P101.QSTRT
- Tag.P101.WINHINCLK
- Tag.P101.XLORL
- Tag.P101.XLORR
- Tag.P101.XSTOPD
- Tag.P101.XSTRTD
- Tag.P101.YSTRT

This counts against the 100 subscription limit, and causes the UI to lag when you are at the maximum subscriptions as well as being way more work to configure if you want to return all tags in a folder.

Attempting to subscribe to Tag.P101 will return an Invalid Address error.

## Preferred solution or suggestions
Enable subscriptions to the root tag.  Looking through the docs, it specifies the return JSON for an object, but maybe this doesn't include FolderType objects.

**Comment by DC2-DanielKrueger** [comment]
Hallo @prairiesnpr , 

I looked into the problem and believe milo does not support subscribing to an object node unless for events created on that node. In fact I believe opcua does not support that at least in the 1.3 version which milo targets with their official releases. 

The only possibility I see is to browse the referenced nodes, collect them and create a MonitoredItem for each of them. 
What attributes of these nodes are interesting for you? Only the Value attribute of the "child" nodes?

Best regards, 
Daniel
