### ISSUE TITLE
XML Namespaces - The xmlns Attribute is missing from the example configuration XML files

### ISSUE THREAD

**Issue by KamielStraatman** [hivemq/hivemq-edge#38]
## Expected layout

```
<hivemq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config.xsd">

        <mqtt-listeners>
            <tcp-listener>.....
```

## Actual file layout
```
<hivemq>
    <mqtt-listeners>
        <tcp-listener>
            <port>1883</port>
```

ahh, makes sense: config.xsd is not there either. But is referenced by default config.xml so....maybe adding this and referencing in the examples xml makes more sense here.

**Comment by simon622** [comment]
Thanks Kamiel - this will be fixed in the 2023.4 release this week.
