### ISSUE TITLE
Include Modbus Function Read Coil

### ISSUE THREAD

**Issue by heinehenning** [hivemq/hivemq-edge#41]
## Problem or use case
Some Modbus Server only allow reading coils. 
## Preferred solution or suggestions
In addition to reading holding registers, other modbus functions like reading coils discrete inputs and input registers should be possible.

**Comment by simon622** [comment]
Hi,

Thanks for the Feedback. We have discussed your request, and this is now being tracked and will be added to the platform soon.

Thanks for your input.

**Comment by DC2-DanielKrueger** [comment]
Hey @heinehenning , 

Reading coils will be able to be read when this is merged : https://github.com/hivemq/hivemq-edge/pull/599. Currently in testing. 

Best Regards, 

Daniel
