### ISSUE TITLE
Add MQTT 3 compatibility for bridges

### ISSUE THREAD

**Issue by simeonthefirst** [hivemq/hivemq-edge#414]
## Problem or use case
We have a use case where we need to publish data from devices to Azure IoT Hub. There is only this [limited Version](https://learn.microsoft.com/en-us/azure/iot/iot-mqtt-5-preview) of IoT Hub that supports MQTT 5. We cannot use this for other reasons.

See also: [HiveMQ community thread](https://community.hivemq.com/t/hivemq-edge-to-azure-iot-hub-unsupported-protocol-version/2857)

## Preferred solution or suggestions
When creating an MQTT Bridge on the Hive MQ Edge, have the possibility to select the MQTT Version.

**Comment by DC2-DanielKrueger** [comment]
Hallo @simeonthefirst 

We had discussions about this. There are some features missing in MQTT 3, e.g. user properties, which we use to avoid endless loops. As a result this is currently no priority as it has some disadvantages. 

Best regards, 
Daniel
