### ISSUE TITLE
Building EmbeddedHiveMQ has no extension

### ISSUE THREAD

**Issue by smtlmoel** [hivemq/hivemq-edge#432]
I have added the HiveMQ Embedded Broker CE to my custom adapter and for this embedded broker I wanted to add an InboundInterceptor.

I set up the embedded broker like told in the docu:
```
final EmbeddedExtension embeddedExtension = EmbeddedExtension.builder()
                .withId("embedded-ext-1")
                .withName("Embedded Extension")
                .withVersion("1.0.0")
                .withPriority(-100)
                .withStartPriority(1000)
                .withAuthor("Me")
                .withExtensionMain(new CustomInterceptor())
                .build();

final EmbeddedHiveMQBuilder embeddedHiveMQBuilder = EmbeddedHiveMQ.builder()
                .withConfigurationFolder(configFile.toPath())
                .withDataFolder(getDataFolder().toPath())
                .withExtensionsFolder(getExtensionFolder().toPath()));

final EmbeddedHiveMQ hiveMQ = embeddedHiveMQBuilder.build();
```

But when I call the build() method of my EmbeddedHiveMQBuilder the function only returns 
an EmbeddedHiveMQImpl() without the embedded ectension.

See file EmbeddedHiveMQBuilderImpl, line 78.

I am not sure if this is intended or needs to be fixed.

**Comment by DC2-DanielKrueger** [comment]
Hey @smtlmoel, thx for raising this. 
I think you are missing to add the embedded extension via ` .withEmbeddedExtension(embeddedExtension)` on the builder. Can you check if this works for you? 

````
        final EmbeddedExtension embeddedExtension = EmbeddedExtension.builder()
                .withId("embedded-ext-1")
                .withName("Embedded Extension")
                .withVersion("1.0.0")
                .withPriority(-100)
                .withStartPriority(1000)
                .withAuthor("Me")
                .withExtensionMain(new CustomInterceptor())
                .build();

        final EmbeddedHiveMQBuilder embeddedHiveMQBuilder = EmbeddedHiveMQ.builder()
                .withEmbeddedExtension(embeddedExtension)
                .withConfigurationFolder(configFile.toPath())
                .withDataFolder(getDataFolder().toPath())
                .withExtensionsFolder(getExtensionFolder().toPath()));

        final EmbeddedHiveMQ hiveMQ = embeddedHiveMQBuilder.build(); 
````

Best regards,
Daniel

**Comment by smtlmoel** [comment]
Hello @DC2-DanielKrueger,

yeah that helped starting an embedded HiveMQ with an extension.

But now I have the follow up problem that the default broker started by the edge and my started embedded broker conflict.

Is there any way to consume incomming messages from the default broker on port 1883, modify these and then publish the transformed message to the internal broker?

Starting the HiveMQ Edge with the hivemq-allow-all-extension does not allow me to connect with an internal client to the default broker and to consume the incomming messages.

Best regards,
Till

**Comment by DC2-DanielKrueger** [comment]
Hello @smtlmoel,
I'm a bit confused how your setup looks like and what you want to achieve? Why are there two instances of Edge running? Can you explain your setup a bit and hopefully I can help you better. You can chain the brokers together using bridges.

Best regards, 
Daniel

**Comment by smtlmoel** [comment]
Hi @DC2-DanielKrueger,

my setup look the way that I start a second broker in my CustomAdapter. The reason is that I have an internal client also running in the CustomAdapter which is subscribed to specific topics. The internal client then stores the incomming messages and after a limit is reached a a new message (batch) containing alle the stored messages is created and published to the bridge.

I have started the second broker because for me it was not possible to connect with the internal client to the default broker. The "batching" is required to reduce the load on the side of the bridge because I receive messages every 200ms.

I hope this makes my case more clear.

Best regards
Till

**Comment by DC2-DanielKrueger** [comment]
Sry I oversaw the reply unfortunately. @smtlmoel 
I do not see a reason why the connection to the "normal" broker should not be possible from within. Are you maybe connecting before the TCP listener is active? 
I would advise to use a single broker as this setup might be really hard to debug. 

Regarding the conflict: You could set one port to 1884 or similar. You also need to set the API port which binds to 8080 per default, to another port. 

I hope I can help you. 

Best regards, 
Daniel

**Comment by DC2-DanielKrueger** [comment]
I close the issue for now, if the problem persists, please re-open it. 

Best regards, 
Daniel
