### ISSUE TITLE
Integrate Apache PLC4X for additional connectors

### ISSUE THREAD

**Issue by JMayrbaeurl** [hivemq/hivemq-edge#53]
## Connectors extensions

Anyone ever thought about integrating or using [Apache PLC4X](https://plc4x.apache.org/) for additional connectors?

**Comment by simon622** [comment]
Thanks for the input, yes, we are actively appraising this. We consider base runtime requirements, transitive dependencies, functionality, licensing and project activity when we decide on which libraries to incorperate and indeed we currently have an abstraction in place for PLC4X that is going through this process. Hope this help to answer your question. Please do let us know of any thoughts you have around this or any other considerations.

**Comment by simon622** [comment]
The abstraction is complete and resides on a branch. No implementations are yet ready to be shipped. We could merge the module to master with build flags or removal of manifest definitions.

**Comment by simon622** [comment]
I cannot merge this branch until the status work is complete so this is pending the merge.

**Comment by simon622** [comment]
This is in master
