### ISSUE TITLE
Show human readable "Last started" column in list of adapters 

### ISSUE THREAD

**Issue by sfrehse** [hivemq/hivemq-edge#63]
## Expected behavior
Show the last started column in a more human-readable for, e.g., "15 days ago", "1h ago"

## Actual behavior
The column only shows the unit "minutes", e.g., "1234 mins ago" which isn't very readable.
![Screenshot 2023-08-31 at 19 09 02](https://github.com/hivemq/hivemq-edge/assets/526283/5b271ea5-2b0c-49b8-ae19-e2cfcd7b0912)

## To Reproduce
Create a protocol adapter and wait for an hour. The respective component sits in the frontend. 

## Details

- Affected HiveMQ Edge version(s): Since 2023.1. 
- Used JVM version: Every

The change is suggested to be implemented it in the frontend since the backend is correctly returning the timestamp.

**Comment by coded9** [comment]
@sfrehse could you assign this to me ?

**Comment by sfrehse** [comment]
> @sfrehse could you assign this to me ?

Sure.
