### ISSUE TITLE
OPC-UA adapter unable to use host.docker.internal URI

### ISSUE THREAD

**Issue by caallinson** [hivemq/hivemq-edge#64]
## Expected behavior

Within the HiveMQ Edge Docker container, hostname ``host.docker.internal`` can be used to connect to an OPC-UA server running on the Docker host machine

## Actual behavior

OPC-UA protocol adapter errors with log message:

ERROR - Not able to connect and subscribe to OPC-UA server opc.tcp://host.docker.internal:49320

java.util.concurrent.CompletionException: java.net.UnknownHostException: {Docker Host Hostname}: No address associated with hostname

Caused by: java.net.UnknownHostException: {Docker Host Hostname}: No address associated with hostname

### Steps

1) Configure OPC-UA server on Docker host machine (probably optional)
2) Start HiveMQ Edge Docker container
3) Configure new OPC-UA Adapter connection to host machine, using ``host.docker.internal`` as hostname

## Details

- Affected HiveMQ Edge version(s): hivemq/hivemq-edge:2023.4
- Used JVM version: openjdk 11.0.19 2023-04-18

**Comment by simon622** [comment]
Thank you for your input, we will look into this issue.

**Comment by caallinson** [comment]
Workaround: 

Docker Compose file, add:
``extra_hosts:
  - "{Docker Host Hostname]:{Docker Host IP Address}"``
  
Change ``host.docker.internal`` to ``{Docker Host Hostname}``

**Comment by vogler75** [comment]
I have the same problem and the workaround does not help with my opcua server running in a container. Would be good to add a "updateEndpointUrl" option, like I did [here ](https://github.com/vogler75/automation-gateway/blob/master/source/lib-core/src/main/kotlin/at/rocworks/gateway/core/opcua/OpcUaDriver.kt).
