### ISSUE TITLE
Wrong installation description for windows

### ISSUE THREAD

**Issue by smtlmoel** [hivemq/hivemq-edge#65]
In the wiki chapter 'Installing HiveMQ Edge/Windows Systems/Manual installation', the first task ist to run `./gradlew clean hivemqZip` but this is no valid gradle task. The actual distribution task should be `./gradlew clean hivemqEdgeZip`.

**Comment by simon622** [comment]
Thank you for raising the issue. We will update the wiki accordingly. Since this is the wiki and there will be no PR, I will attribute your work in the wiki commit.

**Comment by simon622** [comment]
This has been fixed.
